apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: t7d
  name: t7d-delivery
  labels:
    app: t7d-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t7d-delivery

  template:
    metadata:
      labels:
        app:  t7d-delivery
    spec:
      imagePullSecrets:
        - name: nexus-keys
      containers:
        - name: t7d-delivery
          image: docker.galactechstudio.com/t7d_delivery_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3006
---
apiVersion: v1
kind: Service
metadata:
  namespace: t7d
  name: t7d-delivery
spec:
  selector:
    app: t7d-delivery
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 3006
